FROM apache/airflow:3.1.8

USER airflow

RUN pip install --no-cache-dir \
    pandas \
    "requests>=2.31,<3" \
    "urllib3<2.6" \
    psycopg2-binary \
    pyproj \
    openpyxl \
    dbt-core==1.9.0 \
    dbt-postgres==1.9.0